language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - git clone https://github.com/walio/walio.github.io.git public
  - hexo g

after_script:
  - cd ./public
  - git config user.name "walio"
  - git config user.email "userLeeee@gmail.com"
  - git add .
  - git commit -m "Update html"
  - git push "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/walio/walio.github.io.git
